apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ldap-tools-cd
  namespace: argocd
spec:
  project: argo-tutde
  source:
    repoURL: 'https://github.com/tutd3/ldap.git'
    path: cd
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true  # Fixed typo
      prune: true
